---
title: "Perform DE analysis"
subtitle: "Step 1: Compute pseudobulk (PB) profiles"
author: "Shahin Mohammadi"
date: "Run on `r Sys.time()`"
documentclass: article
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
library(ACTIONet)
library(data.table)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(corrplot)
library(muscat)
library(synapser)
library(synExtra)
synLogin(rememberMe = TRUE)
source("functions.R")
})

knitr::opts_chunk$set(
	eval = FALSE,
	error = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	dev = c("png", "pdf"),
	include = FALSE,
	tidy = FALSE
)


```



```{r}
dataset.path = "~/results/datasets/"
figures.path = "~/results/figures"
tables.path = "~/results/tables"
input.path = "~/results/input"


individual_metadata = loadDataset("individual_metadata", dataset.path = dataset.path)

ace = loadDataset("combinedCells_ACTIONet", dataset.path = dataset.path)
sce = as(ace, "SingleCellExperiment")

```

# Use muscat to compute PB profiles
```{r}
sce$cluster_id = ace$Celltype
sce$group_id = ace$Phenotype
sce$sample_id = ace$ID

library(muscat)
sce$id <- paste0(sce$Phenotype, sce$sample_id)
(sce <- prepSCE(sce,
    kid = "cluster_id", # subpopulation assignments
    gid = "group_id",  # group IDs (ctrl/stim)
    sid = "sample_id",   # sample IDs (ctrl/stim.1234)
    drop = TRUE))  # drop all other colData columns

system.time( {pb.logcounts <- aggregateData(sce,
    assay = "logcounts", fun = "mean",
    by = c("cluster_id", "sample_id"))} )

colData(pb.logcounts) = cbind(colData(pb.logcounts), individual_metadata[colnames(pb.logcounts), ])

```


```{r}

storeDataset(pb.logcounts, name = "pseudobulk_mean_logcounts", dataset.path = dataset.path)

```




