---
title: "R Notebook"
output: html_notebook
---

# Setup
```{r include=FALSE}
require(ACTIONet)
require(stringr)
require(ComplexHeatmap)


results.path = "~/results"
input.path = "~/results/input"
dataset.path = "~/results/datasets"
tables.path = "~/results/tables"
figures.path = "~/results/figures"


```

## Enrichment function
```{r}
assess.genesets <-function (arch.gs, terms.gs, N, min.pval = 1e-100, correct = "none"){
    shared = t(sapply(terms.gs, function(gs1) {
        sapply(arch.gs, function(gs2) {
            nn = intersect(gs1, gs2)
        })
    }))
    colnames(shared) = names(arch.gs)
    GS.sizes = sapply(terms.gs, length)
    logPvals.out = sapply(1:ncol(shared), function(i) {
        gg = shared[, i]
        x = as.numeric(sapply(gg, length))
        n.sample = length(arch.gs[[i]])
        n.success = as.numeric(GS.sizes)
        v = rep(1, length(x))
        min.overlap = n.success * n.sample/N
        idx = which(x >= min.overlap)
        if (length(idx) == 0) 
            return(v)
        v[idx] = (phyper(x[idx]-1, n.sample, N-n.sample, n.success[idx], lower.tail = F))
        # v[idx] = HGT_tail(population.size = N, success.count = n.success[idx], 
        #     sample.size = n.sample, observed.success = x[idx])
        return(v)
    })
    if(correct == "global") {
      logPvals.out = matrix(p.adjust(logPvals.out, "fdr"), nrow = nrow(logPvals.out))
    } else if(correct == "local") {
      logPvals.out = apply(logPvals.out, 2, function(x) p.adjust(x, "fdr"))
    }
    rownames(logPvals.out) = names(terms.gs)
    colnames(logPvals.out) = names(arch.gs)
    return(-log10(Matrix::t(logPvals.out)))
}
```

# Load primary datasets
```{r, eval = T}
ACTIONet_summary = readr::read_rds(file.path(dataset.path, "ACTIONet_summary_filtered_individuals.rds"))
pb.logcounts = readr::read_rds(file.path(dataset.path, "PB_mean_logcounts_final.RDS"))

color.df = readRDS(file.path(dataset.path, "celltype_colors.rds"))
colors = color.df$color
names(colors) = color.df$celltype



png("~/Liver_atlas.png", width = 800, height = 600)
plot.ACTIONet(ace3, ace3$Manual_Annotation)
dev.off()


```




# Load DE results
```{r, eval = T}
resDE = readr::read_rds(file.path(dataset.path, "Cohort_specific_DE_results.rds"))
filtered.tables = readr::read_rds(file.path(dataset.path, "Cohort_specific_DE_results_filtered.rds"))
combined.analysis.tables = readr::read_rds(file.path(dataset.path, "meta_analysis_results.rds"))

DE.new = readRDS(file.path(dataset.path, "DE_genes_pseudobulk.rds"))
Up.genes = DE.new$Up.genes
Down.genes = DE.new$Down.genes
DE.sc = DE.new$DE.sc


```

## Annotate archetypes based on cell types
```{r}
arch.annot = annotate.archetypes.using.labels(t(ACTIONet_summary$H_unified), ACTIONet_summary$metadata$Labels)

arch.labels = paste("A", 1:ncol(ACTIONet_summary$H_unified), "-", arch.annot$Label, sep = "")
arch.labels[c(7, 11, 17, 29)] = paste("A", c(7, 11, 17, 29), "-", c("Ex-NRGN", "Ex-SZ", "Ex-SZTR", "In-SZ"), sep = "")

arch.order = c(setdiff(order(match(arch.annot$Label, names(colors))), c(11, 17, 29)), c(11, 17, 29))

```

## Archetypes
```{r}
rdbu_fun = circlize::colorRamp2(c(-3, -1, 0, 1, 3), rev(pals::brewer.rdbu(9)[seq(1, 9, by = 2)]))
Z = scale(t(arch.annot$Enrichment[arch.order, ]))
colnames(Z) = arch.labels[arch.order]

pdf(file.path(figures.path, "archetypes", "celltype_annotation_vs_archetypes_v3.pdf"), width = 8)
Heatmap(Z, cluster_rows = F, cluster_columns = F, rect_gp = gpar(col = "black"), row_names_side = "left", row_names_gp = gpar(col = colors), col = rdbu_fun, name = "Archetypes", column_title = "Archetypes")
dev.off()

```
# Plot cell states
```{r}
cellstates = c(7, 11, 17, 29)
cellstate.titles = c("Ex-NRGN", "Ex-SZ", "Ex-SZTR", "In-SZ")
subH = ACTIONet_summary$H_unified[, cellstates]

ggs = lapply(1:length(cellstates), function(i) {
  gg = plot.ACTIONet.gradient(ACTIONet_summary$ACTIONet2D, subH[, i], alpha_val = 0, point_size = 0.5, grad_palette = "magma") + ggtitle(cellstate.titles[[i]])
  
  return(gg)
})

png(file.path(figures.path, "archetypes", "ACTIONet_cellstates_noNRGN.png"), width = 600*3, height = 600, res = 150)
do.call(gridExtra::grid.arrange, c(lapply(ggs[-1], ggplotify::as.grob), nrow = 1))
dev.off()

png(file.path(figures.path, "archetypes", "ACTIONet_cellstates.png"), width = 800*3, height = 600*3, res = 150)
do.call(gridExtra::grid.arrange, c(lapply(ggs, ggplotify::as.grob), nrow = 2))
dev.off()

sapply(1:4, function(i) {
  png(file.path(figures.path, "archetypes", sprintf("ACTIONet_cellstates_%s.png", cellstate.titles[[i]])), width = 1600, height = 1200, res = 150)
  plot(ggs[[i]])
  dev.off()
})

```

# Plot cell types
```{r}
# cellstats =  c(11, 17, 29)
# idx = setdiff(1:ncol(ACTIONet_summary$H_unified), cellstates)
# subH = ACTIONet_summary$H_unified[, -cellstates]
# Ll = ct.arch.annot$Label[-cellstates]
# perm = order(match(Ll, names(colors)))
# subH = subH[, perm]
# Ll = Ll[perm]
# idx = idx[perm]


idx = setdiff(order(match(arch.annot$Label, names(colors))), c(11, 17, 29))
subH = ACTIONet_summary$H_unified[, idx]


ggs.archs.celltypes = lapply(1:ncol(subH), function(i) {
  gg = plot.ACTIONet.gradient(ACTIONet_summary$ACTIONet2D, subH[, i], alpha_val = 0, point_size = 0.5, grad_palette = "magma") + ggtitle(arch.labels[[arch.order[[i]]]]) +  theme(plot.title = element_text(color = colors[[arch.annot$Label[arch.order[[i]]]]]))
  return(gg)
})


png(file.path(figures.path, "archetypes", "ACTIONet_archetypes_nonstate.png"), width = 800*7, height = 600*4, res = 150)
do.call(gridExtra::grid.arrange, c(lapply(ggs.archs.celltypes, ggplotify::as.grob), nrow = 4))
dev.off()
  
```

```{r}
# data("gProfilerDB_human")

X = gProfilerDB_human$SYMBOL$`GO:BP`
cs = fast_column_sums(X)
X = X[, (cs > 10) & (cs < 2000)]
Y = (ACTIONet_summary$unified_feature_specificity[, c(17, 11, 29)])
arch.BP.enrichment = assess.geneset.enrichment.from.scores(Y, X)$logPvals

colnames(arch.BP.enrichment) = c("Ex-SZTR", "Ex-SZ", "In-SZ")
selected.rows = sort(unique(unlist(as.list(apply(arch.BP.enrichment, 2, function(x) order(x, decreasing = T)[1:5])))))
Heatmap(scale(arch.BP.enrichment)[selected.rows, ])

# plot.top.k.features(arch.BP.enrichment)



```




```{r}
require(openxlsx)

PEC_modules = readLines(con <- file("~/PEC_modules/INT-09_WGCNA_modules_hgnc_ids.csv"))


mod.names = lapply(PEC_modules, function(x) str_split(x, "\t")[[1]][1])
PEC_modules.genes = lapply(PEC_modules, function(x) sort(unique(str_split(x, "\t")[[1]][-1])))
names(PEC_modules.genes) = mod.names

SZ.mods = c("module_3628", "module_3636", "module_3711", "module_3251", "module_1749", "module_2752", "module_3001", "module_3009", "module_3172", "module_3332", "module_3333", "module_3464", "module_3614", "module_725", "module_738", "module_1685", "module_1755", "module_2692", "module_3107", "module_3184", "module_3316", "module_3349", "module_3381", "module_3496", "module_3543", "module_3616", "module_3673", "module_3678", "module_3693", "module_3709", "module_3731")
PEC_modules.genes.SZ = PEC_modules.genes[SZ.mods]


arch.spec = ACTIONet_summary$unified_feature_specificity
associations = do.call(cbind, lapply(PEC_modules.genes, function(mod) as.numeric(rownames(arch.spec) %in% mod)))
colnames(associations) = mod.names
rownames(associations) = rownames(arch.spec)
PEC.mod.en = assess.geneset.enrichment.from.scores(arch.spec, associations)
PEC.mod.logPvals = PEC.mod.en$logPvals
colnames(PEC.mod.logPvals) = colnames(arch.spec)
rownames(PEC.mod.logPvals) = mod.names
  
# plot.top.k.features(PEC.mod.logPvals)


arch.annot = annotate.archetypes.using.labels(t(ACTIONet_summary$H_unified), ACTIONet_summary$metadata$Labels)

arch.labels = paste("A", 1:ncol(ACTIONet_summary$H_unified), "-", arch.annot$Label, sep = "")
arch.labels[c(7, 11, 17, 29)] = paste("A", c(7, 11, 17, 29), "-", c("Ex-NRGN", "Ex-SZ", "Ex-SZTR", "In-SZ"), sep = "")

arch.order = c(setdiff(order(match(arch.annot$Label, names(colors))), c(7, 11, 17, 29)), c(7, 11, 17, 29))

X = PEC.mod.logPvals[SZ.mods, arch.order]
colnames(X) = arch.labels[arch.order]
Heatmap(X, cluster_columns = F)

```


```{r}
associations = do.call(cbind, lapply(DE.new$Down.genes, function(mod) as.numeric(rownames(arch.spec) %in% mod)))
colnames(associations) = names(DE.new$Down.genes)
rownames(associations) = rownames(arch.spec)
PEC.mod.en = assess.geneset.enrichment.from.scores(arch.spec, associations)
PEC.mod.logPvals = PEC.mod.en$logPvals
colnames(PEC.mod.logPvals) = colnames(arch.spec)
rownames(PEC.mod.logPvals) = names(DE.new$Down.genes)
  
# plot.top.k.features(PEC.mod.logPvals)


arch.annot = annotate.archetypes.using.labels(t(ACTIONet_summary$H_unified), ACTIONet_summary$metadata$Labels)

arch.labels = paste("A", 1:ncol(ACTIONet_summary$H_unified), "-", arch.annot$Label, sep = "")
arch.labels[c(7, 11, 17, 29)] = paste("A", c(7, 11, 17, 29), "-", c("Ex-NRGN", "Ex-SZ", "Ex-SZTR", "In-SZ"), sep = "")

arch.order = c(setdiff(order(match(arch.annot$Label, names(colors))), c(7, 11, 17, 29)), c(7, 11, 17, 29))

X = PEC.mod.logPvals[, arch.order]
colnames(X) = arch.labels[arch.order]
Heatmap(X, cluster_columns = F)



```


```{r}
df = data.frame(Gene = rownames(arch.spec), A11 = (arch.spec[, 11]), A29 = (arch.spec[, 29]))
# mask = (df$A11 > 3) & (df$A29 > 3)
# df = df[mask, ]
# df$A11 = (df$A11 - median(df$A11)) / mad(df$A11)
# df$A29 = (df$A29 - median(df$A29)) / mad(df$A29)
df$A11 = scale(df$A11)
df$A29 = scale(df$A29)
df$Label = ""
mask = (df$A11 > 3) & (df$A29 > 3)
df$Label[mask] = df$Gene[mask]

ggscatter(df, "A11", "A29", repel = T, label = "Label")


```


```{r}
bulk = readr::read_rds("~/results/input/MPP_bulk_expression_SZandCON.rds")
bulk.profile = assays(bulk)$voom
bulk.profile.orth = orthoProject(bulk.profile, Matrix::rowMeans(bulk.profile))

```

```{r}
tbl1 = read.csv("~/results/input/Prioritised_PGC3_SZ_Genes.csv", sep = "\t")
PGC3.prioritized.genes = sort(unique(tbl1$Symbol.ID[tbl1$Prioritised == 1]))

tbl2 = read.csv("~/results/input/INT-17_SCZ_High_Confidence_Gene_List.csv", sep = ",")
PEC_HighConf.genes = sort(unique(tbl2$sczgenenames))


A11 = scale(arch.spec[, 11])
A29 = scale(arch.spec[, 29])
mask = (A11 > 4) & (A29 > 4)
arch.genes = rownames(arch.spec)[mask]

pred.genes = list(arch.genes = arch.genes, PEC_HighConf.genes = PEC_HighConf.genes, PGC3.prioritized.genes = PGC3.prioritized.genes)
pred.genes = lapply(pred.genes, function(gs) intersect(gs, rownames(bulk)))

```


```{r}
hot1 <- function (x, y = NULL, mu = 0, paired = FALSE, step_size = 0, 
    skip_check = FALSE) {
    nx <- dim(x)[1]
    ny <- dim(y)[1]
    stat <- fdahotelling:::stat_hotelling_impl(x = x, y = y, mu = mu, paired = paired, 
        step_size = step_size)
    df1 <- min(nx + ny - 2, p)
    df2 <- abs(nx + ny - 2 - p) + 1
    pvalue <- 1 - stats::pf(stat, df1, df2)
    dplyr::data_frame(statName = names(stat), statVal = stat, 
        pValue = pvalue, df1 = df1, df2 = df2)
}

```


```{r}
library(Hotelling)

gs = pred.genes$arch.genes
common.genes = intersect(rownames(bulk.profile.orth), gs)
# Z = apply(t(bulk.profile[gs[1:10], ]) , 2, RNOmni::RankNorm)
X = t(bulk.profile.orth[gs, ])
X1 = X[bulk$Dx == "SCZ", ]
X2 = X[bulk$Dx != "SCZ", ]

stat <- fdahotelling:::stat_hotelling_impl(x = X1, y = X2, mu = 0, paired = F, step_size = 0)
rand.stats = sapply(1:100, function(i) {
  rand.samples = sample(1:nrow(bulk.profile.orth), length(gs))
  randX = t(bulk.profile.orth[rand.samples, ])
  randX1 = randX[bulk$Dx == "SCZ", ]
  randX2 = randX[bulk$Dx != "SCZ", ]
  rand.stat <- fdahotelling:::stat_hotelling_impl(x = randX1, y = randX2, mu = 0, paired = F, step_size = 0)
  
  return(rand.stat)
})

z = (stat - mean(rand.stats) ) / sd(rand.stats)

# require(DescTools)
# out = DescTools::HotellingsT2Test(X1, X2, test = "chi")




```


```{r}

stat <- hot1(x = X1, y = X2, mu = 0, step_size = 0)

# x = Hotelling::hotelling.test(X1, X2)
# 
# 
# N = nx + ny
# print(stat$statVal*(N - p - 1)/((N-2)*p))
# print(x)

```

```{r}



fdahotelling::test_twosample





# X1 = x
# X2 = y
# 

out = fdahotelling::test_twosample(x, y)

stat <- out$statVal
nx = nrow(x)
ny = nrow(y)
p = ncol(x)
df1 <- min(nx + ny - 2, p)
df2 <- abs(nx + ny - 2 - p) + 1
pvalue <- 1 - stats::pf(stat, df1, df2)

dplyr::data_frame(statName = names(stat), statVal = stat, 
    pValue = pvalue)  


stat = Hotelling::hotelling.test(x, y, perm = F)
print(stat)


# pred.scores = cor(bulk.profile[common.genes, ], xx, method = "pearson")



Hot <- function(X1, X2) {
  p = ncol(X1)
  n1 = nrow(X1)
  n2 = nrow(X2)
  
  X1.mean = Matrix::colMeans(X1)
  X2.mean = Matrix::colMeans(X2)
  Delta.means = X1.mean - X2.mean
  
  Delta1 = apply(X1, 1, function(x) x - X1.mean)
  Delta2 = apply(X2, 1, function(x) x - X2.mean)
  Sigma1 = (Delta1 %*% t(Delta1)) / (n1-1)
  Sigma2 = (Delta2 %*% t(Delta2)) / (n2-1)
  Sigma = (n1 - 1) * Sigma1 + (n2 - 1) * Sigma2 / (((1 / n1) + (1 / n2) )*(n1+n2-2))
  
  HT = t(Delta.means) %*% Sigma %*% Delta.means
  
  require(fdahotelling)
  out = fdahotelling::test_twosample(X1, X2, B = 0)
  
  

  
  # x = Hotelling::hotelling.stat(X1, X2)
  
  
  # fdahotelling:::parametric_test
  
  parametric_test
  print(x2)

  x2 = hotelling.stat(X1, X2)
  print(x2)
    
}

x

```


```{r}
common.genes = intersect(rownames(bulk.profile.orth), rownames(U))
xx = arch.spec[common.genes, ]
pred.scores = cor(bulk.profile[common.genes, ], xx, method = "pearson")

sc = apply(pred.scores, 2, function(x) 1 / (1 + exp(-scale(x))))
# sc = apply(pred.scores, 2, function(x) 1 + x)
rownames(sc) =  bulk$SampleID


xx = split(bulk$SampleID, bulk$Dx)
associations = do.call(cbind, lapply(xx, function(mod) as.numeric(bulk$SampleID %in% mod)))
colnames(associations) = names(xx)
rownames(associations) = bulk$SampleID

PEC.mod.logPvals = t(assess.geneset.enrichment.from.scores(sc, associations)$logPvals)
rownames(PEC.mod.logPvals) = 1:nrow(PEC.mod.logPvals)
Heatmap(PEC.mod.logPvals)

```


```{r}
# scores = exp(bulk.profile.orth/10)
scores = 1 / (1 + exp(-bulk.profile.orth))
# scores[scores < 0] = 0
associations = do.call(cbind, lapply(pred.genes, function(gs) as.numeric(rownames(scores) %in% gs)))
colnames(associations) = names(pred.genes)
rownames(associations) = rownames(scores)
pred.scores = t(assess.geneset.enrichment.from.scores(scores, associations)$logPvals)
colnames(pred.scores) = colnames(associations)
rownames(pred.scores) = colnames(scores)


common.genes = intersect(rownames(bulk.profile.orth), rownames(U))
xx = (arch.spec[common.genes, c(29, 11)])
# xx = cbind(sqrt(xx[, 1] * xx[, 2]), xx)
pred.scores = cor(bulk.profile[common.genes, ], xx, method = "pearson")


# pred.scores = sapply(pred.genes, function(gs) stats = scale(Matrix::colMeans(bulk.profile.orth[gs, ])))

df = as.data.frame(scale(pred.scores))
rownames(df) = bulk$SampleID
df$phenotype = bulk$Dx

SZ.samples = list(SZ =  bulk$SampleID[which(bulk$Dx == "SCZ")])
v = df[, 1]
names(v) = rownames(df)
x = fgsea::fgsea(SZ.samples, v)

# fgsea::plotEnrichment(SZ.samples$SZ, v)

print(-log10(x$pval))

# df2 = reshape2::melt(df)
# colnames(df2) = c("phenotype", "method", "z")

# ggbarplot(df2, x = "method", y = "z", color = "phenotype",
#  add = "mean_se", palette = c("#00AFBB", "#E7B800"),
#  position = position_dodge())



```

```{r}
# arch.genes, PEC_HighConf.genes, PGC3.prioritized.genes)

# zz = sapply(pred.genes, function(gs) stats = scale(Matrix::colMeans(bulk.profile.orth[gs, ])))

ll = lapply(pred.genes, function(gs) {
  l = as.numeric(rownames(bulk.profile.orth) %in% gs)
  logPvals=-log10(p.adjust(apply(bulk.profile.orth, 2, function(x) {
    perm = order(x, decreasing = T)
    mhg.out = mhg::mhg_test(l[perm], length(l), sum(l), length(l)/4, 5, upper_bound = F, tol = 1e-300)
    mhg.out$pvalue
  }), method = "fdr"))
})
X = do.call(cbind, ll)

df = as.data.frame(zz)
df$phenotype = bulk$Dx
df2 = reshape2::melt(df)
colnames(df2) = c("phenotype", "method", "z")

# ggbarplot(df2, x = "method", y = "z", color = "phenotype",
#  add = "mean_se", palette = c("#00AFBB", "#E7B800"),
#  position = position_dodge())
# 
# 
# 
# ggbarplot(df, x = "phenotype", y = "arch.genes", fill = "phenotype", palette = c("#666666", "#cccccc"),
#  add = "mean_se", label = TRUE, lab.vjust = -1.6)


perfs = apply(pred.scores, 2, function(x) PRROC::roc.curve(1 / (1 + exp(-scale(x))), weights.class0 = as.numeric(bulk$Dx == "SCZ"), curve = T))
plot_roc(perfs, as.character(pals::brewer.dark2(3)))
# prefs = apply(zz, 2, function(pred) PRROC::roc.curve(pred, weights.class0 = as.numeric(bulk$Dx == "SCZ"), curve = T, sorted = T))

perfs = apply(pred.scores, 2, function(pred) PRROC::pr.curve(pred, weights.class0 = as.numeric(bulk$Dx == "SCZ"), curve = T))
plot_prc(perfs)

# 
# x = sapply(istel.perfs, function(x) x$auc)
# cor(Cat.AC.z, x[names(Cat.AC.z)])
# cor(C1.line.z[names(Cat.AC.z)], Cat.AC.z)
# 
# CPal = as.character(pals::brewer.spectral(length(sorted.istels)))
# AUCs = sapply(istel.perfs, function(x) x$auc)
# perm = order(AUCs, decreasing = T)
# gp = plot_roc(istel.perfs[perm], CPal)



```


```{r}
library(fda)
library(fdahotelling)

SZ.mask = bulk$Dx == "SCZ"
x = t(bulk.profile[pred.genes$arch.genes, SZ.mask])
y = t(bulk.profile[pred.genes$arch.genes, !SZ.mask])

out = fdahotelling::test_twosample(x, y, B = 0)

# Hotelling 
#  750.1352 
# out$statVal

x = t(bulk.profile[pred.genes$PEC_HighConf.genes, SZ.mask])
y = t(bulk.profile[pred.genes$PEC_HighConf.genes, !SZ.mask])

out = fdahotelling::test_twosample(x, y, B = 0, verbose = T)



```


```{r}
l = as.numeric(rownames(bulk.profile.orth) %in% pred.genes$arch.genes)

# logPvals=-log10(p.adjust(apply(bulk.profile.orth, 2, function(x) {
#   perm = order(x, decreasing = T)
#   mhg.out = mhg::mhg_test(l[perm], length(l), sum(l), length(l), 5, upper_bound = F, tol = 1e-300)
#   mhg.out$pvalue
# }), method = "fdr"))

df3 = data.frame(scores = logPvals, phenotype = bulk$Dx)
ggbarplot(df3, x = "phenotype", y = "scores", fill = "phenotype", palette = c("#666666", "#cccccc"),
 add = "mean_se", label = TRUE, lab.vjust = -1.6) + geom_hline(yintercept = -log10(0.05), linetype="dashed", 
                color = "red", size=1)

```



```{r}
Labels = sort(unique(ace.istel$Label))
istel.perfs = vector("list", length(Labels))
names(istel.perfs) = Labels


for(label in Labels) {
  print(label)
  mask.test = ace.istel$Label == label
  
  xgbpred <- predict(PCA.model.full, istel.data.reduced[mask.test, ])
  
  istel.perfs[[label]] = PRROC::roc.curve(xgbpred, weights.class0 = istel.data.labels[mask.test], curve = T)
}

x = sapply(istel.perfs, function(x) x$auc)
cor(Cat.AC.z, x[names(Cat.AC.z)])
cor(C1.line.z[names(Cat.AC.z)], Cat.AC.z)

CPal = as.character(pals::brewer.spectral(length(sorted.istels)))
AUCs = sapply(istel.perfs, function(x) x$auc)
perm = order(AUCs, decreasing = T)
gp = plot_roc(istel.perfs[perm], CPal)

# L = c(istel.perfs, list(LX2 = lx2.perfs))
# CPal = as.character(c(CPal.istel[rownames(X)[order(X[, 4])]], "LX2" = "#aaaaaa"))
# perm = order(sapply(L, function(x) x$auc), decreasing = T)
# gp = plot_roc(L[perm], CPal[perm])


# sort(sapply(L, function(x) x$auc))

pdf("~/figures/TGFb_ROC_pStel_vs_iStel.pdf", width = 12)
print(gp)
dev.off()
```


```{r}
gs = df$Label[df$Label != ""]
gs = gs[-grep("MT-", gs)]




# SZ.genes = readr::read_rds(file.path(input.path, "SCZ_associated_genesets.rds"))
# 
# gs = SZ.genes$

l = as.numeric(rownames(bulk.profile.orth) %in% gs)

logPvals=-log10(p.adjust(apply(bulk.profile.orth, 2, function(x) {
  perm = order(x, decreasing = T)
  mhg.out = mhg::mhg_test(l[perm], length(l), sum(l), length(l), 5, upper_bound = F, tol = 1e-300)
  mhg.out$pvalue
}), method = "fdr"))

df3 = data.frame(scores = logPvals, phenotype = bulk$Dx)
ggbarplot(df3, x = "phenotype", y = "scores", fill = "phenotype", palette = c("#666666", "#cccccc"),
 add = "mean_se", label = TRUE, lab.vjust = -1.6) + geom_hline(yintercept = -log10(0.05), linetype="dashed", 
                color = "red", size=1)

ll = c("CON", "SZ")
isSZ.pred = ll[as.numeric(logPvals > -log10(0.05))+1]
table(isSZ.pred, bulk$Dx)

sum((isSZ.pred == "SZ") & (bulk$Dx == "SCZ")) / sum((bulk$Dx == "SCZ"))

  ## AUC curve ...

```



```{r}
plot.ACTIONet.gradient(ACTIONet_summary$ACTIONet2D, ACTIONet_summary$H_unified[, 30], alpha = 0)
plot.ACTIONet.gradient(ACTIONet_summary$ACTIONet2D, ACTIONet_summary$H_unified[, 6], alpha = 0)


```

