---
title: "Fig3: H-MAGMA analysis"
output: html_notebook
---
# Setup
```{r include=FALSE}
library(org.Hs.eg.db)
require(ACTIONet)
require(stringr)
require(ComplexHeatmap)


results.path = "~/results"
input.path = "~/results/input"
dataset.path = "~/results/datasets"
tables.path = "~/results/tables"
figures.path = "~/results/figures"


```

## Enrichment function
```{r}
assess.genesets <-function (arch.gs, terms.gs, N, min.pval = 1e-100, correct = "none"){
    shared = t(sapply(terms.gs, function(gs1) {
        sapply(arch.gs, function(gs2) {
            nn = intersect(gs1, gs2)
        })
    }))
    colnames(shared) = names(arch.gs)
    GS.sizes = sapply(terms.gs, length)
    logPvals.out = sapply(1:ncol(shared), function(i) {
        gg = shared[, i]
        x = as.numeric(sapply(gg, length))
        n.sample = length(arch.gs[[i]])
        n.success = as.numeric(GS.sizes)
        v = rep(1, length(x))
        min.overlap = n.success * n.sample/N
        idx = which(x >= min.overlap)
        if (length(idx) == 0) 
            return(v)
        v[idx] = (phyper(x[idx]-1, n.sample, N-n.sample, n.success[idx], lower.tail = F))
        # v[idx] = HGT_tail(population.size = N, success.count = n.success[idx], 
        #     sample.size = n.sample, observed.success = x[idx])
        return(v)
    })
    if(correct == "global") {
      logPvals.out = matrix(p.adjust(logPvals.out, "fdr"), nrow = nrow(logPvals.out))
    } else if(correct == "local") {
      logPvals.out = apply(logPvals.out, 2, function(x) p.adjust(x, "fdr"))
    }
    rownames(logPvals.out) = names(terms.gs)
    colnames(logPvals.out) = names(arch.gs)
    return(-log10(Matrix::t(logPvals.out)))
}
```

# Load primary datasets
```{r, eval = T}
ACTIONet_summary = readr::read_rds(file.path(dataset.path, "ACTIONet_summary_filtered_individuals.rds"))
pb.logcounts = readr::read_rds(file.path(dataset.path, "PB_mean_logcounts_final.RDS"))

color.df = readRDS(file.path(dataset.path, "celltype_colors.rds"))
colors = color.df$color
names(colors) = color.df$celltype

```


# Load DE results
```{r, eval = T}
resDE = readr::read_rds(file.path(dataset.path, "Cohort_specific_DE_results.rds"))
filtered.tables = readr::read_rds(file.path(dataset.path, "Cohort_specific_DE_results_filtered.rds"))
combined.analysis.tables = readr::read_rds(file.path(dataset.path, "meta_analysis_results.rds"))

DE.new = readRDS(file.path(dataset.path, "DE_genes_pseudobulk.rds"))
Up.genes = DE.new$Up.genes
Down.genes = DE.new$Down.genes
DE.sc = DE.new$DE.sc
ordered.celltypes = rownames(X)[order(apply(X, 1, sum), decreasing = T)]

```


```{r}
assess.geneset.enrichment.from.archetypes <- function (ace, associations, min.counts = 0, specificity.slot = "unified_feature_specificity") 
{
    if(is.matrix(ace) | is.sparseMatrix(ace)) {
      scores = as.matrix(ace)
    } else {
      scores = rowMaps(ace)[[specificity.slot]]
    }
    if (max(scores) > 100) {
        scores = log1p(scores)
    }
    if (is.list(associations)) {
        associations = sapply(associations, function(gs) as.numeric(rownames(scores) %in% 
            gs))
        rownames(associations) = rownames(scores)
    }
    common.features = intersect(rownames(associations), rownames(scores))
    rows = match(common.features, rownames(associations))
    associations = as(associations[rows, ], "dgCMatrix")
    scores = scores[common.features, ]
    enrichment.out = assess_enrichment(scores, associations)
    rownames(enrichment.out$logPvals) = colnames(associations)
    rownames(enrichment.out$thresholds) = colnames(associations)
    enrichment.out$scores = scores
    return(enrichment.out)
}

annotate.archetypes.using.markers <- function (ace, markers, features_use = NULL, significance_slot = "unified_feature_specificity") 
{
    features_use = ACTIONet:::.preprocess_annotation_features(ace, features_use)
    marker_mat = ACTIONet:::.preprocess_annotation_markers(markers, features_use)
    marker_stats = Matrix::t(assess.geneset.enrichment.from.archetypes(ace, 
        marker_mat, specificity.slot = significance_slot)$logPvals)
    colnames(marker_stats) = colnames(marker_mat)
    marker_stats[!is.finite(marker_stats)] = 0
    annots = colnames(marker_mat)[apply(marker_stats, 1, which.max)]
    conf = apply(marker_stats, 1, max)
    out = list(Label = annots, Confidence = conf, Enrichment = marker_stats)
    return(out)
}
```


```{r}
Up.DE.enrichment = annotate.archetypes.using.markers(ACTIONet_summary$unified_feature_specificity, DE.new$Up.genes)

Y = t(Up.DE.enrichment$Enrichment)
colnames(Y) = paste("A", 1:ncol(X), sep = "")
Rd.pal = circlize::colorRamp2(seq(0, quantile(Y, 0.99), length.out = 8), c("#ffffff", pals::brewer.reds(7)))


Down.DE.enrichment = annotate.archetypes.using.markers(ACTIONet_summary$unified_feature_specificity, DE.new$Down.genes)

X = t(Down.DE.enrichment$Enrichment)
Bu.pal = circlize::colorRamp2(seq(0, quantile(X, 0.99), length.out = 8), c("#ffffff", pals::brewer.blues(7)))

colnames(X) = paste("A", 1:ncol(X), sep = "")

# arch.perm = order(apply(rbind(X, Y), 2, mean), decreasing = T)
# 
# Heatmap(t(Y[, arch.perm]), rect_gp = gpar(col = "black"), col = Rd.pal, cluster_rows = F, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(Y)]), name = "Up", column_title = "Up") + Heatmap(t(X[, arch.perm]), rect_gp = gpar(col = "black"), col = Bu.pal, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(X)]), name = "Down", column_title = "Down")

arch.perm = order(apply(rbind(X), 2, mean), decreasing = T)
Heatmap(t(X[, arch.perm]), cluster_rows = F, rect_gp = gpar(col = "black"), col = Bu.pal, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(X)]), name = "Down", column_title = "Down")


```
```{r}

DE.down.vs.arch.fgsea = apply(ACTIONet_summary$unified_feature_specificity, 2, function(x) {
  fgsea.out = fgsea(DE.new$Down.genes, x, eps = 1e-100)
  
  v = fgsea.out$pval
  names(v) = fgsea.out$pathway
  return(v)
})


X = t(Down.DE.enrichment$Enrichment)
Bu.pal = circlize::colorRamp2(seq(0, quantile(X, 0.99), length.out = 8), c("#ffffff", pals::brewer.blues(7)))

colnames(X) = paste("A", 1:ncol(X), sep = "")

# arch.perm = order(apply(rbind(X, Y), 2, mean), decreasing = T)
# 
# Heatmap(t(Y[, arch.perm]), rect_gp = gpar(col = "black"), col = Rd.pal, cluster_rows = F, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(Y)]), name = "Up", column_title = "Up") + Heatmap(t(X[, arch.perm]), rect_gp = gpar(col = "black"), col = Bu.pal, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(X)]), name = "Down", column_title = "Down")

arch.perm = order(apply(rbind(X), 2, mean), decreasing = T)
Heatmap(t(X[, arch.perm]), cluster_rows = F, rect_gp = gpar(col = "black"), col = Bu.pal, cluster_columns = F, column_names_gp = gpar(col = colors[rownames(X)]), name = "Down", column_title = "Down")

```

