---
title: "Analyze DE genes"
output: html_notebook
---

# Setup
```{r include=FALSE}
require(ACTIONet)
require(stringr)
require(ComplexHeatmap)


dataset.path = "~/results/datasets/"
results.path = "~/results"
figures.folder = "~/results/figures"
input.folder = "~/results/input"


```


# Load primary datasets
```{r}
ACTIONet_summary = readr::read_rds(file.path(dataset.path, "ACTIONet_summary_filtered_individuals.rds"))

pb.logcounts = readr::read_rds(file.path(dataset.path, "PB_mean_logcounts_final.RDS"))

color.df = readRDS(file.path(dataset.path, "celltype_colors.rds"))

colors = color.df$color
names(colors) = color.df$celltype

```

# Load DE results
```{r}
resDE = readr::read_rds(file.path(dataset.path, "Cohort_specific_DE_results_final_with_umi_scaled.rds"))

filtered.tables = readr::read_rds(file.path(dataset.path, "individual_diff_results_filtered_with_umi_scaled.rds"))

combined.analysis.tables = readr::read_rds(file.path(dataset.path, "meta_analysis_diff_results_with_umi_scaled.rds"))

filtered.tables = readr::read_rds(file.path(dataset.path, "individual_diff_results_filtered_full_with_umi_scaled.rds"))


DE.new = readr::read_rds(file.path(dataset.path, "DE_genes_pseudobulk_final_with_umi_scaled.rds"))

Up.genes = DE.new$Up.genes
Down.genes = DE.new$Down.genes
DE.sc = DE.new$DE.sc

```




# Read bulk DE
```{r}
CMC.DE = read.table("~/results/input/CMC_DE_table.csv", header = T)
PEC.DE = read.table("~/results/input/PEC_DE_table.csv", header = T)

common.genes = intersect(rownames(pb.logcounts), intersect(CMC.DE$MAPPED_genes, PEC.DE$gene_name))

CMC.tstat = CMC.DE$t[match(common.genes, CMC.DE$MAPPED_genes)]
PEC.tstat = PEC.DE$SCZ.t.value[match(common.genes, PEC.DE$gene_name)]

names(PEC.tstat) = names(CMC.tstat) = common.genes
pval = cor.test(CMC.tstat, PEC.tstat, method = "spearman")$p.value


```

```{r}
gg = intersect(Reduce("intersect", lapply(resDE$McLean$table$PhenotypeSZ, function(df) df$gene)), Reduce("intersect", lapply(resDE$MtSinai$table$PhenotypeSZ, function(df) df$gene)))

cts = intersect(names(resDE$McLean$table$PhenotypeSZ), names(resDE$MtSinai$table$PhenotypeSZ))

McLean.tstat = do.call(cbind, lapply(1:length(cts), function(i) {
    df1 = resDE$McLean$table$PhenotypeSZ[[cts[[i]]]]
    df2 = resDE$MtSinai$table$PhenotypeSZ[[cts[[i]]]]

    df1 = df1[match(gg, df1$gene), ]
    df2 = df2[match(gg, df2$gene), ]
    
    v=df1$t
    names(v) = df1$gene
    
  mask = (abs(scale(df1$logFC)) > 1) & (abs(scale(df2$logFC)) > 1)
    v[!mask] = 0    
    return(v)
}))

MtSinai.tstat = do.call(cbind, lapply(1:length(cts), function(i) {
    df1 = resDE$McLean$table$PhenotypeSZ[[cts[[i]]]]
    df2 = resDE$MtSinai$table$PhenotypeSZ[[cts[[i]]]]

    df1 = df1[match(gg, df1$gene), ]
    df2 = df2[match(gg, df2$gene), ]
    
    v=df2$t
    names(v) = df1$gene
    
  mask = (abs(scale(df1$logFC)) > 1) & (abs(scale(df2$logFC)) > 1)
    v[!mask] = 0    
    return(v)
}))

# RdBu.pal = circlize::colorRamp2(seq(-0.5, 0.5, length.out = 7), rev(pals::brewer.puor(7)))
CC = cor(McLean.tstat, MtSinai.tstat)
rownames(CC) = colnames(CC) = cts
CC[CC < 0] = 0
ct = intersect(names(resDE$MtSinai$table$PhenotypeSZ), names(resDE$McLean$table$PhenotypeSZ))
pdf("~/results/figures/pairwise_cor_masked_with_umi_scaled.pdf")
Heatmap(CC, cluster_rows = F, cluster_columns = F, name = "Correlation (truncated)", col = blues9, rect_gp = gpar(col = "black"), row_names_side = "left", row_names_gp = gpar(col = colors[rownames(CC)]), column_names_gp = gpar(col = colors[colnames(CC)]))
dev.off()



```


```{r}
library(qvalue)
McLean.Pi1 = sapply(resDE$McLean$table$PhenotypeSZ, function(df) {
  pvals = df$p_val
  pi1 = 1 - qvalue(pvals)$pi0
})

MtSinai.Pi1 = sapply(resDE$MtSinai$table$PhenotypeSZ, function(df) {
  pvals = df$p_val
  pi1 = 1 - qvalue(pvals)$pi0
})
df = data.frame(Celltype = union(names(resDE$MtSinai$table$PhenotypeSZ), names(resDE$McLean$table$PhenotypeSZ)))
df$McLean = McLean.Pi1[df$Celltype]
df$MtSinai = MtSinai.Pi1[df$Celltype]

df2 = reshape2::melt(df)
colnames(df2) = c("Celltype", "Cohort", "Pi1")

df2$Celltype = factor(df2$Celltype, intersect(names(colors), df2$Celltype))

# Genes + mit: 0.13294483 0.04830563
# umis + mit: 0.12460625 0.04745068
print(c(mean(df$McLean[!is.na(df$McLean)]), mean(df$MtSinai[!is.na(df$MtSinai)], rm.na = T)))

require(ggpubr)
gg =ggbarplot(df2, "Celltype", "Pi1", fill = "Cohort", color = "black", palette = rev(pals::brewer.paired(5)),
  position = position_dodge(0.9), xlab = "Celltype", ylab = "Pi1")+ theme(axis.text.x = element_text(face="bold", size=8, angle=90,hjust=0.95,vjust=0.2, color = colors[levels(df2$Celltype)]), axis.text.y = element_text(face="bold", size=12, angle=0), axis.title = element_text(face="bold", size=18, angle=0))

pdf(file.path(figures.folder, "Pi1_with_umi_scaled.pdf"))
plot(gg)
dev.off()


```



```{r}
McLean.PEC.cor.pvals = sapply(resDE$McLean$table$PhenotypeSZ, function(DF) {
  tstats = DF$t
  names(tstats) = DF$gene
  cg = intersect(common.genes, DF$gene)
  x = -log10(cor.test(tstats[cg], PEC.tstat[cg], method = "spearman")$p.value)
  
  return(x)
})


MtSinai.PEC.cor.pvals = sapply(resDE$MtSinai$table$PhenotypeSZ, function(DF) {
  tstats = DF$t
  names(tstats) = DF$gene
  cg = intersect(common.genes, DF$gene)
  x = -log10(cor.test(tstats[cg], PEC.tstat[cg], method = "spearman")$p.value)
  
  return(x)
})


McLean.CMC.cor.pvals = sapply(resDE$McLean$table$PhenotypeSZ, function(DF) {
  tstats = DF$t
  names(tstats) = DF$gene
  cg = intersect(common.genes, DF$gene)
  x = -log10(cor.test(tstats[cg], CMC.tstat[cg], method = "spearman")$p.value)
  
  return(x)
})


MtSinai.CMC.cor.pvals = sapply(resDE$MtSinai$table$PhenotypeSZ, function(DF) {
  tstats = DF$t
  names(tstats) = DF$gene
  cg = intersect(common.genes, DF$gene)
  x = -log10(cor.test(tstats[cg], CMC.tstat[cg], method = "spearman")$p.value)
  
  return(x)
})

df = data.frame(Celltypes = names(resDE$MtSinai$table$PhenotypeSZ), McLean.PEC = McLean.PEC.cor.pvals[names(resDE$MtSinai$table$PhenotypeSZ)], MtSinai.PEC = MtSinai.PEC.cor.pvals[names(resDE$MtSinai$table$PhenotypeSZ)], McLean.CMC = McLean.CMC.cor.pvals[names(resDE$MtSinai$table$PhenotypeSZ)], MtSinai.CMC = MtSinai.CMC.cor.pvals[names(resDE$MtSinai$table$PhenotypeSZ)])
df$Combined = combine.logPvals(t(as.matrix(df[, -1])))
df = df[order(df$Combined, decreasing = T), ]

df = df[, 1:3]

df2 = reshape2::melt(df)
colnames(df2) = c("Celltype", "Test", "Enrichment")
df2$Test = factor(as.character(df2$Test), c("McLean.PEC", "MtSinai.PEC", "McLean.CMC", "MtSinai.CMC"))
# df2$Celltype = factor(df2$Celltype, df$Celltypes[order(pmax(cbind(df$McLean.PEC, df$MtSinai.PEC)), decreasing = T)])
df2$Celltype = factor(df2$Celltype, intersect(names(colors), df$Celltypes))

require(ggpubr)
gg =ggbarplot(df2, "Celltype", "Enrichment", fill = "Test", color = "black", palette = rev(pals::brewer.paired(5)),
  position = position_dodge(0.9), xlab = "Celltype", ylab = "Enrichment")+ theme(axis.text.x = element_text(face="bold", size=8, angle=90,hjust=0.95,vjust=0.2, color = colors[levels(df2$Celltype)]), axis.text.y = element_text(face="bold", size=12, angle=0), axis.title = element_text(face="bold", size=18, angle=0))

pdf(file.path(figures.folder, "DE_vs_bulk_with_umi_scaled.pdf"))
plot(gg)
dev.off()




```



## Overlap among DE genes of different archetypes
### Compute pairwise  overlap using RRHO
```{r}
library(RRHO)
library(gplots)

	cts = names(DE.new$Up.genes)
	DE.overlap.RRHO.mats = vector("list", length(cts)*length(cts))
	
	for(i1 in 1:length(cts)) {
	  ct1 = cts[[i1]]
    DE.results1 = filtered.tables[[ct1]]$McClean
	  df1 = data.frame(Gene = DE.results1$gene, tstats = DE.results1$t)
	
	  for(i2 in 1:length(cts)) {
  	  ct2 = cts[[i2]]
      DE.results2 = filtered.tables[[ct1]]$MtSinai
      # DE.results2 = resDE$MtSinai$table$PhenotypeSZ[[ct2]]
  	  df2 = data.frame(Gene = DE.results2$gene, tstats = DE.results2$t)
	    
  	  
	    R.utils::printf("\t%s vs %s ... ", ct1, ct2)
	    
	    n1 = paste("McLean", ct1, sep = "_")
	    n2 = paste("MtSinai", ct2, sep = "_")
	    
	    RRHO.example = RRHO(df1, df2, outputdir= file.path(results.path, "RRHO"), alternative="enrichment", labels=c(n1, n2), BY=TRUE, log10.ind=TRUE, plot=TRUE)
	    
	    idx = (i1-1)*length(cts)+i2
	    DE.overlap.RRHO.mats[[idx]] = apply(t(RRHO.example[[4]]),1,rev)
	    
	    # DE.overlap.RRHO.mats[[(i2-1)*length(ct)+i1]] = DE.overlap.RRHO.mats[[(i1-1)*length(ct)+i2]]
	    
	    # Heatmap(apply(t(RRHO.example[[4]]),1,rev), cluster_columns = F, cluster_rows = F)
	    # 
	    R.utils::printf("%.2f (%d)\n", max(DE.overlap.RRHO.mats[[idx]]), idx)
	      
	  }
	}

	
	
	saveRDS(DE.overlap.RRHO.mats, file.path(results.path, "DE_overlap_RRHO.RDS"))


```

### Plot RRHO heatmaps as a grid
```{r}
require(viridis)
gradPal_fun = circlize::colorRamp2(c(5, 50, 100, 200, 250, 350), viridis::viridis(6))


# pdf(sprintf("%s/Limma_tstat_RRHO.pdf",  width = 30, height = 30)
png(sprintf("%s/tstat_RRHO_v3.png", figures.folder), width = 10000, height = 10000, res = 300)
pushViewport(viewport(layout = grid.layout(20, 20)))

i = 0
for(r in 1:length(cts)) {
  ht = c()
  for(c in 1:length(cts)) {
    idx = (r-1)*length(cts)+c
    X = DE.overlap.RRHO.mats[[idx]]
    X[X > 350] = 350
    ht = Heatmap(X, cluster_rows = F, cluster_columns = F, col = gradPal_fun, show_heatmap_legend = FALSE, gap = 0, column_gap = 0)
    
    pushViewport(viewport(layout.pos.col=c, layout.pos.row=r))
    draw(ht, newpage = FALSE) # or draw(ht_list, newpage = FALSE)
    popViewport()
  }  
}
dev.off()


```




```{r}
SZ.genes = readr::read_rds(file.path(input.folder, "SCZ_associated_genesets.rds"))

```

## Total number of DE genes
```{r}
Up.genes.overlap = sapply(Up.genes, function(gs) intersect(gs, SZ.genes$`Up.genes (PEC)`))
Up.genes.size = sapply(Up.genes.overlap, length) # 287 unique genes (14% of DE up bulk)

Down.genes.overlap = sapply(Down.genes, function(gs) intersect(gs, SZ.genes$`Down.genes (PEC)`))
Down.genes.size = sapply(Down.genes.overlap, length) # 475 unique genes (26.5% of DE down bulk)

celltype.colors = colors[names(Up.genes)]
# names(celltype.colors) = names(Up.genes)

df.Up = data.frame(Counts = sapply(Up.genes, function(x) length(setdiff(x, SZ.genes$`DE.Up (PEC)`))), Celltype = names(Up.genes), Direction="Up", Color = celltype.colors[names(Up.genes)], stringsAsFactors = F)

df.UpandBulk = data.frame(Counts = sapply(Up.genes, function(x) length(intersect(x, SZ.genes$`DE.Up (PEC)`))), Celltype = names(Up.genes), Direction="Up & Bulk", Color = celltype.colors[names(Up.genes)], stringsAsFactors = F)


df.Down = data.frame(Counts = -sapply(Down.genes, function(x) length(setdiff(x, SZ.genes$`DE.Down (PEC)`))), Celltype = names(Down.genes), Direction="Down", Color = celltype.colors[names(Down.genes)], stringsAsFactors = F)

df.DownandBulk = data.frame(Counts = -sapply(Down.genes, function(x) length(intersect(x, SZ.genes$`DE.Down (PEC)`))), Celltype = names(Down.genes), Direction="Down & Bulk", Color = celltype.colors[names(Down.genes)], stringsAsFactors = F)



df = rbind(df.Up, df.UpandBulk, df.Down, df.DownandBulk)

total.Up = sapply(Up.genes, length)
total.Down = sapply(Down.genes, length)

set.seed(0)
total = total.Up + total.Down + 0.001*rnorm(length(Up.genes))

arch.perm = order(total, decreasing = F)
df$Celltype = factor(df$Celltype, names(total)[arch.perm])

pdf(file.path(figures.folder, "NumDysregGenes_with_umi_scaled.pdf"), width = 8, height = 5)
ggplot(data = df, aes(x = Celltype, y = Counts, fill = Direction)) + geom_bar(stat = "identity")+
  coord_flip()+ylab("Sorted Celltypes")+
labs(y = "# Genes", x = "Sorted Celltypes")+
  theme_minimal()+
  guides(fill = FALSE)+ scale_fill_manual(values=c("#3288bd", colorspace::darken("#3288bd", 0.35), "#d53e4f", colorspace::darken("#d53e4f", 0.35))) + theme(axis.text.y = element_text(face="bold", color=celltype.colors[levels(df$Celltype)], size=12, angle=0), axis.text.x = element_text(face="bold", color="black", size=12, angle=0), axis.title = element_text(face="bold", size=14, angle=0))
dev.off()





```
# Functional enrichment
## Load annotations
```{r}
FunCat = readRDS(file.path(dataset.path, "FunCat.rds"))

FunCat.genes = split(FunCat$FunCat2Gene$Gene, factor(FunCat$FunCat2Gene$Category, unique(FunCat$FunCat2Gene$Category)))[-15]
names(FunCat.genes) = FunCat$FunCat2Class$Category

FunCat.annotation = FunCat$FunCat2Class$Classification

FunCatPal = ggpubr::get_palette("npg", length(unique(FunCat.annotation)))
names(FunCatPal) = unique(FunCat.annotation)


```
## Perform enrichment

```{r}
assess.genesets <-function (arch.gs, terms.gs, N, min.pval = 1e-100, correct = NULL){
    shared = t(sapply(terms.gs, function(gs1) {
        sapply(arch.gs, function(gs2) {
            nn = intersect(gs1, gs2)
        })
    }))
    colnames(shared) = names(arch.gs)
    GS.sizes = sapply(terms.gs, length)
    logPvals.out = sapply(1:ncol(shared), function(i) {
        gg = shared[, i]
        x = as.numeric(sapply(gg, length))
        n.sample = length(arch.gs[[i]])
        n.success = as.numeric(GS.sizes)
        v = rep(1, length(x))
        min.overlap = n.success * n.sample/N
        idx = which(x >= min.overlap)
        if (length(idx) == 0) 
            return(v)
        v[idx] = (phyper(x[idx], n.sample, N-n.sample, n.success[idx], lower.tail = F))
        # v[idx] = HGT_tail(population.size = N, success.count = n.success[idx], 
        #     sample.size = n.sample, observed.success = x[idx])
        return(v)
    })
    if(correct == "global") {
      logPvals.out = matrix(p.adjust(logPvals.out, "fdr"), nrow = nrow(logPvals.out))
    } else if(correct == "local") {
      logPvals.out = apply(logPvals.out, 2, function(x) p.adjust(x, "fdr"))
    }
    rownames(logPvals.out) = names(terms.gs)
    colnames(logPvals.out) = names(arch.gs)
    return(-log10(Matrix::t(logPvals.out)))
}
```


```{r}
Up.enrichment.GS = assess.genesets(Up.genes, SZ.genes, nrow(pb.logcounts), correct = "global")
Down.enrichment.GS = assess.genesets(Down.genes, SZ.genes, nrow(pb.logcounts), correct = "global")


Dd = cbind(Up.enrichment.GS[, 5], Down.enrichment.GS[, 6])
colnames(Dd) = c("Up", "Down")
write.table(Dd, file.path(results.path, "DE_overlap_with_bulk.tsv"), sep = "\t", row.names = T, col.names = T, quote = F)


```


```{r}
Up.enrichment = assess.genesets(FunCat.genes, Up.genes[1:17], nrow(pb.logcounts), correct = "global")
Down.enrichment = assess.genesets(FunCat.genes, Down.genes[1:17], nrow(pb.logcounts), correct = "global")

Up.enrichment[Up.enrichment < -log10(0.05)] = 0
Down.enrichment[Down.enrichment < -log10(0.05)] = 0

ha_rows = rowAnnotation(df = list("Class" = FunCat.annotation), col = list("Class" = FunCatPal), annotation_legend_param = list("Class"=list(title_gp = gpar(fontsize = 0), labels_gp = gpar(fontsize = 10))))


X.U = (Up.enrichment)
# redCol_fun = circlize::colorRamp2(c(quantile(X.U, 0.25), quantile(X.U, 0.5), quantile(X.U, 0.85), quantile(X.U, 0.99)), c("#ffffff", "#fee5d9", "#ef3b2c", "#99000d"))
redCol_fun = circlize::colorRamp2(c(0, exp(quantile(log(X.U)[X.U > 2], seq(0.01, 0.95, length.out = 12)))), c("#ffffff", pals::brewer.reds(12)))

X.D = (Down.enrichment)
# blueCol_fun = circlize::colorRamp2(c(quantile(X.D, 0.25), quantile(X.U, 0.5), quantile(X.D, 0.85), quantile(X.D, 0.99)), c( "#ffffff", "#9ecae1", "#2171b5", "#08306b"))

blueCol_fun = circlize::colorRamp2(c(0, exp(quantile(log(X.D)[X.D > 2], seq(0.01, 0.95, length.out = 12)))), c("#ffffff", pals::brewer.blues(12)))

# pals::brewer.reds()


pdf(file.path(figures.folder, "DE_FunCat_enrichment_meta_filtered_with_umi_scaled_neuro.pdf"), width = 14, height = 7)
par(mar=c(0,150,0,0))
Heatmap(X.U, rect_gp = gpar(col = "black"), name = "Up", column_title = "Up-regulated", cluster_rows = F, cluster_columns = F, col = redCol_fun, row_names_side = "left",  column_names_gp = gpar(fontsize = 14, fontface="bold", col = colors[colnames(X.U)]), row_names_gp = gpar(fontsize = 14, fontface="bold", col = FunCatPal[FunCat.annotation]), column_title_gp = gpar(fontsize = 18, fontface="bold"), row_title_gp = gpar(fontsize = 18, fontface="bold"), row_names_max_width = unit(150, "cm"), column_names_max_height = unit(150, "cm"))+
Heatmap(X.D, rect_gp = gpar(col = "black"), name = "Down", cluster_rows = F, cluster_columns = F, col = blueCol_fun, row_names_side = "left", column_title = "Down-regulated",  column_names_gp = gpar(fontsize = 14, fontface="bold", col = colors[colnames(X.D)]), row_names_gp = gpar(fontsize = 14, fontface="bold", col = FunCatPal[FunCat.annotation]), column_title_gp = gpar(fontsize = 18, fontface="bold"), row_title_gp = gpar(fontsize = 18, fontface="bold"), right_annotation = ha_rows, row_names_max_width = unit(150, "cm"), column_names_max_height = unit(150, "cm"))
dev.off()

```



```{r}
gp.stringent.up = gProfileR::gprofiler(DE.new$Up.genes, hier_filtering = "strong", src_filter = c("GO:BP"))
gp.moderate.up = gProfileR::gprofiler(DE.new$Up.genes, hier_filtering = "moderate", src_filter = c("GO:BP"))
gp.none.up = gProfileR::gprofiler(DE.new$Up.genes, hier_filtering = "none", src_filter = c("GO:BP"))


gp.stringent.down = gProfileR::gprofiler(DE.new$Down.genes, hier_filtering = "strong", src_filter = c("GO:BP"))
gp.moderate.down = gProfileR::gprofiler(DE.new$Down.genes, hier_filtering = "moderate", src_filter = c("GO:BP"))
gp.none.down = gProfileR::gprofiler(DE.new$Down.genes, hier_filtering = "none", src_filter = c("GO:BP"))

# 
# 
# common.terms.id = sort(unique(union(gp.none.up$term.id, gp.none.down$term.id)))

data("gProfilerDB_human")
BP = gProfilerDB_human$SYMBOL$`GO:BP`

gp.combined = rbind(gp.none.up, gp.none.down)
gp.combined = gp.combined[gp.combined$term.name %in% colnames(BP), ]

write.table(gp.combined, file.path(results.path, "Combined_DE_BP_enrichment.tsv"), sep = "\t", row.names = F, col.names = T, quote = F)

common.terms.id = sort(unique(gp.combined$term.id))
selected.cols = match(gp.combined$term.name[match(common.terms.id, gp.combined$term.id)], colnames(BP))

common.terms.names = colnames(BP)[selected.cols]



library(simplifyEnrichment)
GOSemSim = GO_similarity(common.terms.id)


# compare_clustering_methods(GOSemSim, plot_type = "heatmap")

set.seed(0)
pdf(file.path(figures.folder, "GO_simplified.pdf"), width = 10)
GOdf = simplifyGO(GOSemSim)
dev.off()

GOdf2 = GOdf[order(GOdf$cluster), ]


go.cl = split(GOdf$term, GOdf$cluster)
GOdf2 = GOdf2[GOdf2$cluster %in% which(sapply(go.cl, length) > 2), ]
GOdf2$row = match(GOdf2$cluster, unique(GOdf2$cluster))

write.table(GOdf2, file.path(results.path, "Combined_DE_BP_clusters.tsv"), sep = "\t", row.names = F, col.names = T, quote = F)


go.cl = go.cl[sapply(go.cl, length) > 2]

dfs = split(gp.none.up, gp.none.up$query.number)
Up.go.cl.enrichment = matrix(0, nrow = length(go.cl), ncol = length(Up.genes))
colnames(Up.go.cl.enrichment) = names(Up.genes)
for(i in 1:length(dfs)) {
  df = dfs[[i]]
  for(j in 1:length(go.cl)) {
    kk = which(df$term.name %in% go.cl[[j]])
    if(length(kk) == 0) {
      next 
    } else {
      Up.go.cl.enrichment[j, names(dfs)[[i]]] = combine.logPvals(as.matrix(-log10(df$p.value[kk])))
    }
  }
}

dfs = split(gp.none.down, gp.none.down$query.number)
Down.go.cl.enrichment = matrix(0, nrow = length(go.cl), ncol = length(Down.genes))
colnames(Down.go.cl.enrichment) = names(Down.genes)
for(i in 1:length(dfs)) {
  df = dfs[[i]]
  for(j in 1:length(go.cl)) {
    kk = which(df$term.name %in% go.cl[[j]])
    if(length(kk) == 0) {
      next 
    } else {
      Down.go.cl.enrichment[j, names(dfs)[[i]]] = combine.logPvals(as.matrix(-log10(df$p.value[kk])))
    }
  }
}


# go.cl = split(df$term, df$cluster)
# go.cl.genes = lapply(go.cl, function(terms) {
#   terms = intersect(terms, colnames(BP))
#   if(length(terms) == 1) {
#     selected.rows = which(BP[, terms] > 0)
#   } else {
#     selected.rows = which(fast_column_sums(BP[, terms]) > 0)
#   }
#   rownames(BP)[selected.rows]
# })
# Up.go.cl.enrichment = assess.genesets(go.cl.genes, Up.genes, nrow(pb.logcounts))
# Down.go.cl.enrichment = assess.genesets(go.cl.genes, Down.genes, nrow(pb.logcounts))



# MPal = pals::polychrome(length(TF.mods))
# names(MPal) = paste("BP_M", 1:length(TF.mods), sep = "")
# ha_row = rowAnnotation(Module = factor(unlist(lapply(1:length(TF.mods), function(i) paste("BP_M", rep(i, length(TF.mods[[i]])), sep = ""))), paste("BP_M", 1:length(TF.mods), sep = "")), col = list(Module = MPal))


X.U = (Up.go.cl.enrichment)
# redCol_fun = circlize::colorRamp2(c(quantile(X.U, 0.25), quantile(X.U, 0.5), quantile(X.U, 0.85), quantile(X.U, 0.99)), c("#ffffff", "#fee5d9", "#ef3b2c", "#99000d"))
redCol_fun = circlize::colorRamp2(c(0, exp(quantile(log(X.U)[X.U > 2], seq(0.05, 0.95, length.out = 12)))), c("#ffffff", pals::brewer.reds(12)))

X.D = (Down.go.cl.enrichment)
# blueCol_fun = circlize::colorRamp2(c(quantile(X.D, 0.25), quantile(X.U, 0.5), quantile(X.D, 0.85), quantile(X.D, 0.99)), c( "#ffffff", "#9ecae1", "#2171b5", "#08306b"))

blueCol_fun = circlize::colorRamp2(c(0, exp(quantile(log(X.D)[X.D > 2], seq(0.05, 0.95, length.out = 12)))), c("#ffffff", pals::brewer.blues(12)))

pdf(file.path(figures.folder, "GO_modules_enrichment.pdf"), width = 12, height = 6)
Heatmap(Up.go.cl.enrichment, rect_gp = gpar(col = "black"), cluster_columns = F, cluster_rows = F, column_title = "Up", column_title_gp = gpar(fontsize = 12), column_names_gp = gpar(col = colors[colnames(TF.up)]), name = "Up", col = redCol_fun) + Heatmap(Down.go.cl.enrichment, rect_gp = gpar(col = "black"), cluster_columns = F, cluster_rows = F, column_title = "Down", column_title_gp = gpar(fontsize = 12), column_names_gp = gpar(col = colors[colnames(TF.down)]), name = "Down", row_names_side = "left", col = blueCol_fun)
dev.off()

```

